#!/bin/sh

set -eu

# Write out our systemd service to unblock wifi
rsync ../kiosk-conf/unblock-wifi.service $1/etc/systemd/system/unblock-wifi.service

mkdir -p $1/etc/wpa_supplicant

# Write out our systemd service to start our wifi setup service
cat ../kiosk-conf/wifi_setup.service.tpl | sed \
   -e "s|<KIOSK_HOMEPAGE_URL>|$IGconf_kiosk_homepage_url|g" \
   > $1/etc/systemd/system/wifi_setup.service


# # Enable the wifi_setup service so it starts automatically
$BDEBSTRAP_HOOKS/enable-units "$1" wifi_setup

# We'll run chromium like this
# Install the kiosk launch script
ROTATION=${IGconf_kiosk_rotation:-normal}
cat ../kiosk-conf/kiosk-launch.sh.tpl | sed \
   -e "s|<KIOSK_ROTATION>|$ROTATION|g" \
   > $1/usr/local/bin/kiosk-launch.sh
chmod +x $1/usr/local/bin/kiosk-launch.sh

# We'll run our wrapper script
APP="/usr/local/bin/kiosk-launch.sh"

# Write out our systemd kiosk service
cat ../kiosk-conf/kiosk.service.tpl | sed \
    -e "s|<KIOSK_USER>|$IGconf_device_user1|g" \
    -e "s|<KIOSK_RUNDIR>|\/home\/$IGconf_device_user1|g" \
    -e "s|<KIOSK_APP>|$APP|g" \
    > $1/etc/systemd/system/kiosk.service

# # Enable the kiosk service so it starts automatically
$BDEBSTRAP_HOOKS/enable-units "$1" kiosk

# Mask getty on tty1 to prevent login prompt
systemctl --root=$1 mask getty@tty1.service