#!/bin/bash

set -eu

# configure the splashscreen
mkdir -p $1/usr/share/plymouth/themes/KioskOs
chmod 755 $1/usr/share/plymouth/themes/KioskOs

rsync -a ${IGIMAGE}/plymouth/themes/KioskOs $1/usr/share/plymouth/themes/

chmod 644 $1/usr/share/plymouth/themes/KioskOs/*

# set the default theme to KioskOs
chroot $1 plymouth-set-default-theme KioskOs
